/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common"
  
export declare namespace TrustCart {
      
    export type ItemStruct = {id: BigNumberish, name: string, category: string, image: string, price: BigNumberish, ratings: BigNumberish, stock: BigNumberish, exists: boolean}

    export type ItemStructOutput = [id: bigint, name: string, category: string, image: string, price: bigint, ratings: bigint, stock: bigint, exists: boolean] & {id: bigint, name: string, category: string, image: string, price: bigint, ratings: bigint, stock: bigint, exists: boolean }
  

    export type OrderStruct = {orderId: BigNumberish, itemId: BigNumberish, timeStamp: BigNumberish, pricePaid: BigNumberish}

    export type OrderStructOutput = [orderId: bigint, itemId: bigint, timeStamp: bigint, pricePaid: bigint] & {orderId: bigint, itemId: bigint, timeStamp: bigint, pricePaid: bigint }
  
    }

  export interface TrustCartInterface extends Interface {
    getFunction(nameOrSignature: "addStock" | "buyItem" | "getItem" | "getOrder" | "items" | "listItem" | "orderCount" | "orders" | "owner" | "storeName" | "totalItems" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExcessAmountRefund" | "ItemListed" | "ItemPurchased" | "StockAdded" | "Withdrawal" | "constructorEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'addStock', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyItem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getItem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOrder', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'items', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'listItem', values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'orderCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'orders', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'storeName', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalItems', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addStock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'items', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orderCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'orders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalItems', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ExcessAmountRefundEvent {
      export type InputTuple = [buyer: AddressLike, orderId: BigNumberish, itemId: BigNumberish, amountRefunded: BigNumberish];
      export type OutputTuple = [buyer: string, orderId: bigint, itemId: bigint, amountRefunded: bigint];
      export interface OutputObject {buyer: string, orderId: bigint, itemId: bigint, amountRefunded: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemListedEvent {
      export type InputTuple = [itemId: BigNumberish, name: string, price: BigNumberish, stock: BigNumberish];
      export type OutputTuple = [itemId: bigint, name: string, price: bigint, stock: bigint];
      export interface OutputObject {itemId: bigint, name: string, price: bigint, stock: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, orderId: BigNumberish, itemId: BigNumberish, pricePaid: BigNumberish];
      export type OutputTuple = [buyer: string, orderId: bigint, itemId: bigint, pricePaid: bigint];
      export interface OutputObject {buyer: string, orderId: bigint, itemId: bigint, pricePaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StockAddedEvent {
      export type InputTuple = [itemId: BigNumberish, stockAmount: BigNumberish];
      export type OutputTuple = [itemId: bigint, stockAmount: bigint];
      export interface OutputObject {itemId: bigint, stockAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace constructorEventEvent {
      export type InputTuple = [owner: AddressLike, name: string, totalItems: BigNumberish];
      export type OutputTuple = [owner: string, name: string, totalItems: bigint];
      export interface OutputObject {owner: string, name: string, totalItems: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TrustCart extends BaseContract {
    
    connect(runner?: ContractRunner | null): TrustCart;
    waitForDeployment(): Promise<this>;

    interface: TrustCartInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addStock: TypedContractMethod<
      [_itemId: BigNumberish, _stock: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buyItem: TypedContractMethod<
      [_itemId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getItem: TypedContractMethod<
      [_itemId: BigNumberish, ],
      [TrustCart.ItemStructOutput],
      'view'
    >
    

    
    getOrder: TypedContractMethod<
      [buyer: AddressLike, _orderId: BigNumberish, ],
      [TrustCart.OrderStructOutput],
      'view'
    >
    

    
    items: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean] & {id: bigint, name: string, category: string, image: string, price: bigint, ratings: bigint, stock: bigint, exists: boolean }],
      'view'
    >
    

    
    listItem: TypedContractMethod<
      [_name: string, _category: string, _image: string, _price: BigNumberish, _ratings: BigNumberish, _stock: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    orderCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    orders: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {orderId: bigint, itemId: bigint, timeStamp: bigint, pricePaid: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    storeName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalItems: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addStock'): TypedContractMethod<
      [_itemId: BigNumberish, _stock: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyItem'): TypedContractMethod<
      [_itemId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getItem'): TypedContractMethod<
      [_itemId: BigNumberish, ],
      [TrustCart.ItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOrder'): TypedContractMethod<
      [buyer: AddressLike, _orderId: BigNumberish, ],
      [TrustCart.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'items'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean] & {id: bigint, name: string, category: string, image: string, price: bigint, ratings: bigint, stock: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'listItem'): TypedContractMethod<
      [_name: string, _category: string, _image: string, _price: BigNumberish, _ratings: BigNumberish, _stock: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'orderCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'orders'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {orderId: bigint, itemId: bigint, timeStamp: bigint, pricePaid: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'storeName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalItems'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ExcessAmountRefund'): TypedContractEvent<ExcessAmountRefundEvent.InputTuple, ExcessAmountRefundEvent.OutputTuple, ExcessAmountRefundEvent.OutputObject>;
getEvent(key: 'ItemListed'): TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
getEvent(key: 'ItemPurchased'): TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
getEvent(key: 'StockAdded'): TypedContractEvent<StockAddedEvent.InputTuple, StockAddedEvent.OutputTuple, StockAddedEvent.OutputObject>;
getEvent(key: 'Withdrawal'): TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
getEvent(key: 'constructorEvent'): TypedContractEvent<constructorEventEvent.InputTuple, constructorEventEvent.OutputTuple, constructorEventEvent.OutputObject>;

    filters: {
      
      'ExcessAmountRefund(address,uint256,uint256,uint256)': TypedContractEvent<ExcessAmountRefundEvent.InputTuple, ExcessAmountRefundEvent.OutputTuple, ExcessAmountRefundEvent.OutputObject>;
      ExcessAmountRefund: TypedContractEvent<ExcessAmountRefundEvent.InputTuple, ExcessAmountRefundEvent.OutputTuple, ExcessAmountRefundEvent.OutputObject>;
    

      'ItemListed(uint256,string,uint256,uint256)': TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
      ItemListed: TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
    

      'ItemPurchased(address,uint256,uint256,uint256)': TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
      ItemPurchased: TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
    

      'StockAdded(uint256,uint256)': TypedContractEvent<StockAddedEvent.InputTuple, StockAddedEvent.OutputTuple, StockAddedEvent.OutputObject>;
      StockAdded: TypedContractEvent<StockAddedEvent.InputTuple, StockAddedEvent.OutputTuple, StockAddedEvent.OutputObject>;
    

      'Withdrawal(address,uint256)': TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
      Withdrawal: TypedContractEvent<WithdrawalEvent.InputTuple, WithdrawalEvent.OutputTuple, WithdrawalEvent.OutputObject>;
    

      'constructorEvent(address,string,uint256)': TypedContractEvent<constructorEventEvent.InputTuple, constructorEventEvent.OutputTuple, constructorEventEvent.OutputObject>;
      constructorEvent: TypedContractEvent<constructorEventEvent.InputTuple, constructorEventEvent.OutputTuple, constructorEventEvent.OutputObject>;
    
    };
  }